const BASE_URL = process.env.REACT_APP_API_BASE_URL;
const PRODUCT_API = process.env.REACT_APP_PRODUCT_API;
const ORDER_API = process.env.REACT_APP_ORDER_API;
const CUSTOMER_API = process.env.REACT_APP_CUSTOMER_API;
const SUPPLIER_API = process.env.REACT_APP_SUPPLIER_API;
const ORDER_ITEM_API = process.env.REACT_APP_ORDER_ITEM_API;
const STOCK_MOVEMENT_API = process.env.REACT_APP_STOCK_MOVEMENT_API;
const STOCK_API = process.env.REACT_APP_STOCK_API;
const CATEGORY_API = process.env.REACT_APP_CATEGORY_API;

export {
  BASE_URL,
  PRODUCT_API,
  ORDER_API,
  CUSTOMER_API,
  SUPPLIER_API,
  ORDER_ITEM_API,
  STOCK_MOVEMENT_API,
  STOCK_API,
  CATEGORY_API
};
